project:
  type: website
  pre-render:
    - python3 scripts/check_quarto_collisions.py

website:
  title: "protocols.heeg.io"
  site-url: https://kpc002.github.io/protocols-website
  twitter-card: true
  page-navigation: true
  repo-url: https://github.com/kpc002/protocols-website
  repo-actions: [edit, issue]
  search:
    location: navbar
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: protocols/
        text: Protocols
      - contribute.md
  sidebar:
    collapse-level: 1
    search: true
    style: "docked"
    contents: 
      - auto: protocols/**
      - text: "---"
      - contribute.md
  
format:
  html:
    theme:
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]
    toc: true
    code-line-numbers: false
    link-external-icon: true
    link-external-newwindow: true

editor: source

execute:
  freeze: auto
