project:
  type: website

website:
  title: "protocols.heeg.io"
  site-url: https://protocols.heeg.io
  twitter-card: true
  page-navigation: true
  repo-url: https://github.com/maximilian-heeg/protocols.heeg.io
  repo-actions: [edit, issue]
  search:
    location: sidebar
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: protocols/
        text: Protocols
      - contribute.md
  sidebar:
    collapse-level: 1
    search: true
    style: "docked"
    contents: 
      - auto: protocols/**
      - text: "---"
      - contribute.md
  
format:
  html:
    theme:
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]
    toc: true
    code-line-numbers: false
    include-in-header:
      - umami.js
    link-external-icon: true
    link-external-newwindow: true

editor: source

execute:
  freeze: auto